### ISSUE TITLE
"Today" doesn't change when the day changes

### ISSUE THREAD

**Issue by tuukka** [HSLdevcom/digitransit-ui#1359] opened 2017-02-18 15:27 UTC
When you keep the search results summary page open through midnight or longer, it keeps saying "Today" although the day it refers to changes to yesterday, the day before yesterday etc. This can be misleading.

**Comment by ebalink** [comment] 2017-02-18 19:03
The date changes only if you choose "now" ("time.-navingation-now-btn"). Changing the origin or destination don't affect the date, even though it would be quite safe to assume that if the saved "today" date and the actual current date differ and even the whole searched itinerary changes, the use case is a whole new.

The chosen date is shown on the next page but I think it's safe to assume that at that point most users' focus is on the route and in exact minutes etc. and not on the date.

This is a problem especially in mobile devices where the address bar is quite short and, by default, usually shows only the page domain. So user doesn't event see the request params that are still affecting. It's also common to assume that this kind of variables are reset when one reloads the page. 

The issue is a bit critical in a way that e.g. a friend of mine almost missed a train (saved by a taxi) today because Reittiopas had instructed to use a bus line that wasn't even operated on weekends.

**Comment by vesameskanen** [comment] 2018-01-15 07:31
Fixed in https://github.com/HSLdevcom/digitransit-ui/releases/tag/20171228

**Closed by vesameskanen** 2018-01-15 07:31 UTC
Labels: bug
